### ISSUE TITLE
Warning: Already linked: /usr/local/Cellar/opencv/3.4.0_1

### ISSUE THREAD

**Issue by aloveric** [SixQuant/nowatermark#2]
ImportError: No module named cv2
```

$ brew link --force opencv3
Warning: Already linked: /usr/local/Cellar/opencv/3.4.0_1
To relink: brew unlink opencv && brew link opencv

brew unlink opencv && brew link opencv
Unlinking /usr/local/Cellar/opencv/3.4.0_1... 139 symlinks removed
Linking /usr/local/Cellar/opencv/3.4.0_1... 139 symlinks created


```

执行完还是 ImportError: No module named cv2

**Comment by aloveric** [comment]
`brew unlink opencv && brew link opencv
Unlinking /usr/local/Cellar/opencv/3.4.0_1... 139 symlinks removed
Linking /usr/local/Cellar/opencv/3.4.0_1... 139 symlinks created
`

**Comment by diegobona** [comment]
我也遇到相同问题！和前面安装opencv时的warning是否有关系：
🍺  /usr/local/Cellar/tbb/2018_U2: 128 files, 2MB
Warning: opencv: this formula has no --c++11 option so it will be ignored!
Warning: opencv: this formula has no --with-contrib option so it will be ignored!
Warning: opencv: this formula has no --with-python3 option so it will be ignored!
Warning: opencv: this formula has no --without-python option so it will be ignored!

**Comment by SixQuant** [comment]
这个可能和你的环境有关系，删干净再重装吧
$ brew update
$ brew uninstall opencv3
$ rm -rf /usr/local/Cellar/opencv3
或许和你们的Python版本也有关系？

**Comment by aloveric** [comment]
已测试通过
